import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

const SHOTS: {
  src: string;
  alt: string;
  tag: string;
  caption: string;
  sub: string;
}[] = [
  {
    src: "/screenshots/results.png",
    alt: "Dashboard results, AI-scored job matches with verdict, strengths and gaps",
    tag: "Results",
    caption: "Ranked matches, scored against your resume",
    sub: "Every role gets a verdict, a 1-10 fit score, concrete strengths and gaps.",
  },
  {
    src: "/screenshots/jobs.png",
    alt: "All jobs view, filterable list with search and verdict filters",
    tag: "Jobs",
    caption: "Every match, searchable and filterable",
    sub: "Filter by verdict, search by company or title, drill into any role for an on-demand deep dive.",
  },
  {
    src: "/screenshots/deep-dive.png",
    alt: "Per-job deep dive panel, agent-generated company brief, gap analysis, cover letter and resume rewrites",
    tag: "Deep dive",
    caption: "An agent that researches each role on demand",
    sub: "Company brief, gap analysis, tailored cover letter, and resume rewrites — generated by a Claude tool-use agent in 30–90s.",
  },
  {
    src: "/screenshots/progress.png",
    alt: "Live hunt progress, fetching, filtering and scoring stages",
    tag: "Live run",
    caption: "Watch the agent work, live",
    sub: "Each stage streams as it happens, including scoring N of 30.",
  },
  {
    src: "/screenshots/profile.png",
    alt: "Profile and preferences, titles, skills and search window",
    tag: "Profile",
    caption: "Your titles, skills and search window",
    sub: "Per-user preferences drive what gets surfaced and how it is scored.",
  },
  {
    src: "/screenshots/companies.png",
    alt: "Companies tracked, 93 companies across three ATS platforms",
    tag: "Companies",
    caption: "93 companies tracked",
    sub: "Across Greenhouse, Lever and Ashby, tagged by ATS and India-HQ.",
  },
  {
    src: "/screenshots/resume.png",
    alt: "Resume page, AI-parsed candidate profile",
    tag: "Resume",
    caption: "Your resume, parsed into a profile",
    sub: "Claude reads your resume into a structured profile used for scoring.",
  },
];

const TECH = [
  "Next.js 16",
  "TypeScript",
  "Tailwind v4",
  "shadcn/ui",
  "Claude Sonnet 4.6",
  "Anthropic SDK",
  "Postgres",
  "Drizzle ORM",
];

export default function LandingPage() {
  return (
    <main className="flex-1">
      {/* Hero */}
      <section className="container mx-auto px-6 pt-24 pb-16 md:pt-32 md:pb-20 max-w-3xl text-center">
        <div className="inline-flex items-center gap-2 mb-6 px-3 py-1 text-xs font-medium rounded-full border bg-muted/40 text-muted-foreground">
          <span className="size-1.5 rounded-full bg-emerald-500" />
          Private alpha, invite only
        </div>
        <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-6">
          Hunterr
        </h1>
        <p className="text-lg md:text-2xl text-muted-foreground mb-10 leading-relaxed">
          An AI job-discovery agent. Scans 93 company job boards, ranks roles
          against your resume with Claude.
        </p>
        <div className="flex flex-col sm:flex-row gap-3 justify-center">
          <Button size="lg" nativeButton={false} render={<Link href="/signin" />}>
            Sign in
          </Button>
          <Button
            variant="outline"
            size="lg"
            nativeButton={false}
            render={<Link href="#how-it-works" />}
          >
            See how it works
          </Button>
        </div>
      </section>

      {/* How it works */}
      <section
        id="how-it-works"
        className="container mx-auto px-6 py-20 max-w-5xl"
      >
        <h2 className="text-3xl md:text-4xl font-bold text-center mb-3">
          How it works
        </h2>
        <p className="text-muted-foreground text-center mb-12 max-w-xl mx-auto">
          A four-stage pipeline. Cheap upstream filtering and ranking keep the
          expensive scoring step focused on jobs worth analyzing.
        </p>
        <div className="grid sm:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <div className="text-xs font-medium text-muted-foreground mb-1">
                Step 01
              </div>
              <CardTitle>Crawl</CardTitle>
              <CardDescription className="pt-2">
                Pulls every posting from Greenhouse, Lever and Ashby across 85
                companies with active India hiring.
              </CardDescription>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground">
              About 9,000 postings fetched in parallel in seconds. No scraping,
              no auth.
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <div className="text-xs font-medium text-muted-foreground mb-1">
                Step 02
              </div>
              <CardTitle>Filter</CardTitle>
              <CardDescription className="pt-2">
                Your titles, skills, location and posting age. Geofenced US and
                Canada remote roles are auto-rejected.
              </CardDescription>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground">
              Thousands of postings narrow to a shortlist of real matches.
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <div className="text-xs font-medium text-muted-foreground mb-1">
                Step 03
              </div>
              <CardTitle>Rank</CardTitle>
              <CardDescription className="pt-2">
                A cheap Claude Haiku pass reads your profile and ranks the
                matches by seniority fit and skill overlap, keeping the best 30.
              </CardDescription>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground">
              No tokens wasted scoring roles you would never get.
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <div className="text-xs font-medium text-muted-foreground mb-1">
                Step 04
              </div>
              <CardTitle>Score with Claude</CardTitle>
              <CardDescription className="pt-2">
                Each of the 30 goes to Claude Sonnet 4.6 with your resume for a
                verdict, a 1-10 fit score, strengths and gaps.
              </CardDescription>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground">
              Resume prompt-cached, so a full run costs roughly 20 to 50 cents.
            </CardContent>
          </Card>
        </div>
      </section>

      {/* Product showcase */}
      <section className="container mx-auto px-6 py-20 max-w-4xl">
        <h2 className="text-2xl md:text-3xl font-bold text-center mb-16">
          See it in action
        </h2>

        {/* Single column. Centered caption above an app-window framed shot. */}
        <div className="space-y-24">
          {SHOTS.map((shot, i) => (
            <figure key={shot.src} className="flex flex-col items-center">
              <figcaption className="text-center max-w-xl mb-6">
                <div className="text-xs font-mono uppercase tracking-[0.2em] text-muted-foreground mb-3">
                  {String(i + 1).padStart(2, "0")} &middot; {shot.tag}
                </div>
                <h3 className="text-2xl md:text-3xl font-semibold tracking-tight">
                  {shot.caption}
                </h3>
                <p className="mt-3 text-sm md:text-base text-muted-foreground leading-relaxed">
                  {shot.sub}
                </p>
              </figcaption>

              {/* App-window frame */}
              <div className="w-full rounded-xl border border-border bg-card overflow-hidden shadow-2xl shadow-black/50">
                <div className="flex items-center gap-2 h-9 px-4 border-b border-border bg-muted/30">
                  <span className="size-2.5 rounded-full bg-red-500/60" />
                  <span className="size-2.5 rounded-full bg-yellow-500/60" />
                  <span className="size-2.5 rounded-full bg-green-500/60" />
                </div>
                <Image
                  src={shot.src}
                  alt={shot.alt}
                  width={2000}
                  height={1100}
                  className="w-full h-auto"
                  priority={i === 0}
                />
              </div>
            </figure>
          ))}
        </div>
      </section>

      {/* Tech stack */}
      <section className="container mx-auto px-6 py-16 max-w-3xl text-center">
        <h2 className="text-2xl font-bold mb-2">Built with</h2>
        <p className="text-sm text-muted-foreground mb-6">
          A modern, deployable stack.
        </p>
        <div className="flex flex-wrap justify-center gap-2 text-sm">
          {TECH.map((tech) => (
            <span
              key={tech}
              className="px-3 py-1 rounded-md border bg-muted/30 text-muted-foreground"
            >
              {tech}
            </span>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="container mx-auto px-6 py-10 mt-12 border-t border-border text-center text-sm text-muted-foreground">
        Built by Nishin S, {new Date().getFullYear()}
      </footer>
    </main>
  );
}
